# Programming for Data Analysis: Assignment 1
 

## Describtion of the numby.random package


 The numby.random package, part of the NumPy  allows users to create random numbers quickly using python. 
 ![NumPy](img/numpy.PNG "NumPy (source: numby.org)") 
 
 The numby.random package is more versatile then the in-built python random command as it allows for the creation of random arrays and probability distributions.

numby.random commands can be split into types, these are;

-  Simple random data
-  Permutations
-  Distributions
-  Random generator

An over of these commands and their uses will be discussed below. 




### Simple Random data


The list of ten commands below can generate random numbers in different sizes and formats depending on ones requirements.


![Simple Random DataCommand List ](img/SRData.png "(source: scipy.org)")

An example of the randint command in use is demostrated below.

In [2]:
import numpy as np
np.random.randint(11,high=15, size=25)


array([11, 12, 14, 13, 11, 13, 12, 12, 12, 13, 14, 12, 12, 11, 12, 14, 14,
       13, 12, 11, 11, 13, 12, 14, 12])

This command has filled an array of 25  with random integers between 11 and 15,changing this command slightly was can get a difffernt array format. 


In [24]:
np.random.randint(1, high=17, size=(6, 3))

array([[14,  5, 14],
       [ 1,  4, 14],
       [14, 15,  1],
       [10, 12,  9],
       [ 3,  7, 15],
       [14,  6, 16]])

As can be seen from the example above, these command are use when one is looking to create new random content, the next set of command can be used when one wants to randomise already existing content 

### Permutations
Below is the list of permutation commands availible in the numby.random package, these commands can re-order the sequence of existing numbers. 
![Permutaion commands ](img/Perm.PNG "(source:scipy.org)")

The use of the premution commands can be seen below, where the numbers 1, 4, 9, 12 & 15 care arrange in a random order. 

In [3]:
 np.random.permutation([1, 4, 9, 12, 15])


array([ 4,  1, 15,  9, 12])

In [4]:
 np.random.permutation([1, 4, 9, 12, 15])


array([ 9,  1,  4, 15, 12])

### Distributions
Below is a selection of commands from the distribution list of commands, these commands allow one to use random saples from a particular distrpution type.
![Distributions (source: scipy.org)](img/dist.PNG)

Below the beta distubtion command is used to create an array of 6 random numbers with such a distribution. 


In [12]:
np.random.beta(3, 9, size=6)

array([0.23761618, 0.09066975, 0.19502483, 0.12279826, 0.39277204,
       0.33539189])